apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv 
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /mnt/data
    server: 172.31.1.171
    readOnly: false
~                   
