apiVersion: v1
kind: Service
metadata:
  namespace: lab4a
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  namespace: lab4a
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext: 
        supplementalGroups: [5555]
      containers:
      - name: nginx
        securityContext:
          runAsUser: 65534
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www-nfs-claim
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      namespace: lab4a
      name: www-nfs-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-storage
      resources:
        requests:
          storage: 1Gi

